### ISSUE TITLE
SocketException: OS Error: Connection refused, errno = 61, address = localhost, port = 54372

### ISSUE THREAD

**Issue by bartonhammond** [stablekernel/aqueduct_examples#6]
Steps:

- Start Flutter on iOS simulator
- Start Aqueduct
- Enter `username` and `password` and click `Register`
<img width="348" alt="screen shot 2019-01-07 at 5 06 42 pm" src="https://user-images.githubusercontent.com/1282364/50798634-a8584280-129e-11e9-9b0a-d6850a3bc1fa.png">

Flutter client terminal:
```
Upgrading project.pbxproj of Runner.app' to include the 'flutter_assets' directory
Removing app.flx from project.pbxproj since it has been replaced with flutter_assets.
Xcode build done.                                            9.3s
[VERBOSE-2:shell.cc(184)] Dart Error: Unhandled exception:
SocketException: OS Error: Connection refused, errno = 61, address = localhost, port = 54372
#0      _rootHandleUncaughtError.<anonymous closure> (dart:async/zone.dart:1112:29)
#1      _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#2      _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
[VERBOSE-2:shell.cc(184)] Dart Error: Unhandled exception:
SocketException: OS Error: Connection refused, errno = 61, address = localhost, port = 54372
#0      _rootHandleUncaughtError.<anonymous closure> (dart:async/zone.dart:1112:29)
#1      _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#2      _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
```
Aqueduct terminal:
```
[server]$ aqueduct serve
-- Aqueduct CLI Version: 3.1.0+1
-- Aqueduct project version: 3.1.0+1
-- Preparing...
-- Starting application 'todo/todo'
    Channel: Todo
    Config: /Users/bartonhammond/projects/aqueduct_examples/todo/server/config.yaml
    Port: 8888
[INFO] aqueduct: Server aqueduct/1 started.
[INFO] aqueduct: Server aqueduct/2 started.
[INFO] aqueduct: Server aqueduct/3 started.
[INFO] aqueduct: Server aqueduct/4 started.
```

**Comment by bartonhammond** [comment]
Oops...port is 8082.

**Comment by husseinm19** [comment]
same
